# syntax=docker/dockerfile:1
ARG VOLTO_VERSION
FROM plone/frontend-dev:${VOLTO_VERSION}

ARG ADDON_NAME
ARG ADDON_PATH

COPY --chown=node:node package.json /app/src/addons/${ADDON_PATH}/

# Copy linter / prettier configs
COPY --chown=node:node .eslintignore* .prettierignore* /app/
COPY --chown=node:node .eslintrc-patch.js /app/.eslintrc.js

RUN <<EOT
    /setupAddon
    yarn install --network-timeout 1000000
EOT

EXPOSE 6006
