name: 'Setup Frontend'
description: 'Setup frontend codebase'
inputs:
  node-version:
    description: 'Node Version'
    required: true
    default: '22.x'
  working-directory:
    description: 'Working directory to use'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable corepack
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        npm i -g corepack@latest
        corepack enable

    - name: Get pnpm store directory
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install project dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: make install