import React from 'react';
import FlickrView from './DefaultView';
import Wrapper from '@plone/volto/storybook';

const withWrapper = (Story, { args }) => {
  return (
    <Wrapper anonymous>
      <div style={{ width: '1000px' }}>
        <Story {...args} />
      </div>
    </Wrapper>
  );
};

export default {
  title: 'Public/Blocks/FlickrBlock',
  component: FlickrView,
  decorators: [withWrapper],
  parameters: {
    controls: { expanded: true },
    docs: {
      description: {
        component:
          'Embeds a Flickr post/gallery using the Flickr embed script. Provide the embed code as generated by Flickr.',
      },
    },
  },
  argTypes: {
    flickrId: {
      name: 'Flickr embed code',
      control: 'text',
    },
    align: {
      name: 'Alignment',
      control: 'select',
      options: ['center', 'left', 'right'],
    },
    size: {
      name: 'Size',
      control: 'select',
      options: ['s', 'm', 'l'],
    },
  },
  args: {
    flickrId:
      '<a data-flickr-embed="true" data-header="true" data-footer="true" href="https://www.flickr.com/photos/plone-foundation/albums/72177720303069181" title="Plone Conference 2022 Namur"><img src="https://live.staticflickr.com/65535/52443622430_c442b75502.jpg" width="500" height="375" alt="Plone Conference 2022 Namur"/></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>',
    align: 'center',
    size: 'l',
  },
};

export const AlignLeft = {
  args: {
    align: 'left',
  },
};
export const AlignCenter = {
  args: {
    align: 'center',
  },
};
export const AlignRight = {
  args: {
    align: 'right',
  },
};
