name: Code analysis checks
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  codeanalysis:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v4

      - name: Setup Frontend
        uses: ./.github/actions/setup_frontend
        with:
          node-version: ${{ inputs.node-version }}

      - name: Linting
        run: make lint
