name: "Volto Social Blocks: CI"
description: "Main workflow for Volto Social Blocks"

on:
  push:
  workflow_dispatch:


jobs:
  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  code-analysis:
    name: "Code analysis checks"
    uses: ./.github/workflows/code.yml
    needs:
        - config
    with:
        node-version: ${{ needs.config.outputs.node-version }}

  unit:
    name: "Run unit tests"
    uses: ./.github/workflows/unit.yml
    needs:
        - config
    with:
        node-version: ${{ needs.config.outputs.node-version }}

  i18n:
    name: "Run i18n checks"
    uses: ./.github/workflows/i18n.yml
    needs:
        - config
    with:
        node-version: ${{ needs.config.outputs.node-version }}

  acceptance:
    name: "Acceptance tests"
    uses: ./.github/workflows/acceptance.yml
    needs:
      - config
      - code-analysis
      - unit
      - i18n
    with:
      node-version: ${{ needs.config.outputs.node-version }}

  storybook:
    name: "Storybook"
    uses: ./.github/workflows/storybook.yml
    needs:
        - config
        - code-analysis
        - unit
        - i18n
    with:
        node-version: ${{ needs.config.outputs.node-version }}

  report:
    name: "Final report"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - config
      - code-analysis
      - unit
      - i18n
      - acceptance
      - storybook
    steps:
      - name: Write report
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| config | ${{ needs.config.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| code-analysis | ${{ needs.code-analysis.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| unit | ${{ needs.unit.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| i18n | ${{ needs.i18n.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| acceptance | ${{ needs.acceptance.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| storybook | ${{ needs.storybook.result }} |' >> $GITHUB_STEP_SUMMARY
