name: Storybook

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Frontend
        uses: ./.github/actions/setup_frontend
        with:
          node-version: ${{ inputs.node-version }}

      - name: Generate Storybook
        run: |
          make storybook-build

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: .storybook-build
